dfdcc

diff --git a/.github/workflows/what_time_is_it.yml b/.github/workflows/what_time_is_it.yml
--- a/.github/workflows/what_time_is_it.yml
+++ b/.github/workflows/what_time_is_it.yml
@@ -23,17 +23,25 @@ jobs:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v2
         
       - name: Run coding style check
         run: |
-          check.sh $(pwd) $(pwd)
+          ./check.sh $(pwd) $(pwd)
           
       - name: Display coding style errors
         if: always()
         run: |
-          if [ -f coding-style-reports.log ]; then
-            cat coding-style-reports.log
+          CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
+          for ERRORS in $CODING_STYLE_ERRORS; do
+            array=(`echo $ERRORS | sed 's/:/\n/g'`)
+            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
+          done
+          if [[ -n $CODING_STYLE_ERRORS ]]
+          then
+            exit 1
+          else
+            echo No coding style errors detected
           fi
           
       - name: Fail if coding style errors found
